cxx_binary(
  name = 'example',
  srcs = [
    'example.cpp',
  ],
  compiler_flags = [
    '-std=c++14',
  ],
  deps = [
    '//:spdlog',
  ],
)

cxx_binary(
  name = 'bench',
  srcs = [
    'bench.cpp',
  ],
  compiler_flags = [
    '-std=c++14',
  ],
  deps = [
    '//:spdlog',
  ],
)
