CXX	= clang++
CXXFLAGS	= -march=native -Wall -Wextra -Wshadow -pedantic -std=c++11 -pthread -I../include -B/usr/lib/gold-ld/
CXX_RELEASE_FLAGS = -O3 -flto 
CXX_DEBUG_FLAGS= -g 

OUTBIN  = example-clang

all: example.cpp
	$(CXX) example.cpp -o $(OUTBIN) $(CXXFLAGS) $(CXX_RELEASE_FLAGS)
	

debug: example.cpp
	$(CXX) example.cpp -o $(OUTBIN)-debug $(CXXFLAGS) $(CXX_DEBUG_FLAFS)



clean:
	rm -f *.txt $(OUTBIN) $(OUTBIN)-debug
	
rebuild: clean all
rebuild-debug: clean debug


