CXX	= g++
CXXFLAGS	= -march=native -Wall -Wextra -Wshadow -pedantic -std=c++11 -pthread -I../include 
CXX_RELEASE_FLAGS = -O3 -flto
CXX_DEBUG_FLAGS= -g 

OUTBIN  = bench

all: bench.cpp
	$(CXX) bench.cpp -o $(OUTBIN) $(CXXFLAGS) $(CXX_RELEASE_FLAGS)
	

debug: bench.cpp
	$(CXX) bench.cpp -o $(OUTBIN)-debug $(CXXFLAGS) $(CXX_DEBUG_FLAGS)



clean:
	rm -f *.txt $(OUTBIN) $(OUTBIN)-debug


rebuild: clean all
rebuild-debug: clean debug


