#!/bin/sh

if [ $# -lt 1 ]; then
  echo "usage: $0 <program>"
fi

PROG=$1

if [ ! -x "$PROG" ]; then
  echo $PROG not found or not executable.
  exit 1
fi

$* &
PID=$!

while `kill -0 $PID 2>/dev/null`; do
  ps -eo size,pid,user,pcpu,command --sort -size | awk '{ line=1 ; hr=$1/1024 ; printf("%13.2f Mb ",hr); } { for ( x=4 ; x<=NF ; x++ ) { printf("%s ",$x) } print "" }' | grep -v grep | grep -v $0 | grep $PROG
done
